### ISSUE TITLE
Create a Readme file on how to start the application for development

### ISSUE THREAD

**Issue by AlDrag** [AlDrag/poller-koajs#4]

**Comment by Anushkasandaruwan** [comment]
Can I??

**Comment by AlDrag** [comment]
No problem! Go for it :)

**Comment by Anushkasandaruwan** [comment]
I'm getting following error when I tried npm start.

```
node --use-strict ./app/app.js

poller-koajs/app/app.js:16
api.get('/polls', async (ctx, next) => {
                        ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by AlDrag** [comment]
@Anushkasandaruwan I think it's because you are using an older nodejs version. Think it needs to be at least version 8 to run koajs without polyfills. I should have put that restriction in the package.json file:)
